Removed app.config from the project because it was causing a compilation error.
git-svn-id: https://opendentalsoft.com:23793/svn/opendental/head@9462 098d0599-7f2b-0410-95a5-ad30ac85393a